/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/_prisma_migrations": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter._prisma_migrations.id"];
          checksum?: parameters["rowFilter._prisma_migrations.checksum"];
          finished_at?: parameters["rowFilter._prisma_migrations.finished_at"];
          migration_name?: parameters["rowFilter._prisma_migrations.migration_name"];
          logs?: parameters["rowFilter._prisma_migrations.logs"];
          rolled_back_at?: parameters["rowFilter._prisma_migrations.rolled_back_at"];
          started_at?: parameters["rowFilter._prisma_migrations.started_at"];
          applied_steps_count?: parameters["rowFilter._prisma_migrations.applied_steps_count"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["_prisma_migrations"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** _prisma_migrations */
          _prisma_migrations?: definitions["_prisma_migrations"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter._prisma_migrations.id"];
          checksum?: parameters["rowFilter._prisma_migrations.checksum"];
          finished_at?: parameters["rowFilter._prisma_migrations.finished_at"];
          migration_name?: parameters["rowFilter._prisma_migrations.migration_name"];
          logs?: parameters["rowFilter._prisma_migrations.logs"];
          rolled_back_at?: parameters["rowFilter._prisma_migrations.rolled_back_at"];
          started_at?: parameters["rowFilter._prisma_migrations.started_at"];
          applied_steps_count?: parameters["rowFilter._prisma_migrations.applied_steps_count"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter._prisma_migrations.id"];
          checksum?: parameters["rowFilter._prisma_migrations.checksum"];
          finished_at?: parameters["rowFilter._prisma_migrations.finished_at"];
          migration_name?: parameters["rowFilter._prisma_migrations.migration_name"];
          logs?: parameters["rowFilter._prisma_migrations.logs"];
          rolled_back_at?: parameters["rowFilter._prisma_migrations.rolled_back_at"];
          started_at?: parameters["rowFilter._prisma_migrations.started_at"];
          applied_steps_count?: parameters["rowFilter._prisma_migrations.applied_steps_count"];
        };
        body: {
          /** _prisma_migrations */
          _prisma_migrations?: definitions["_prisma_migrations"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/language": {
    get: {
      parameters: {
        query: {
          project_id?: parameters["rowFilter.language.project_id"];
          file?: parameters["rowFilter.language.file"];
          code?: parameters["rowFilter.language.code"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["language"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** language */
          language?: definitions["language"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          project_id?: parameters["rowFilter.language.project_id"];
          file?: parameters["rowFilter.language.file"];
          code?: parameters["rowFilter.language.code"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          project_id?: parameters["rowFilter.language.project_id"];
          file?: parameters["rowFilter.language.file"];
          code?: parameters["rowFilter.language.code"];
        };
        body: {
          /** language */
          language?: definitions["language"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/project": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.project.id"];
          name?: parameters["rowFilter.project.name"];
          created_at?: parameters["rowFilter.project.created_at"];
          api_key?: parameters["rowFilter.project.api_key"];
          created_by_user_id?: parameters["rowFilter.project.created_by_user_id"];
          base_language_code?: parameters["rowFilter.project.base_language_code"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["project"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** project */
          project?: definitions["project"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.project.id"];
          name?: parameters["rowFilter.project.name"];
          created_at?: parameters["rowFilter.project.created_at"];
          api_key?: parameters["rowFilter.project.api_key"];
          created_by_user_id?: parameters["rowFilter.project.created_by_user_id"];
          base_language_code?: parameters["rowFilter.project.base_language_code"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.project.id"];
          name?: parameters["rowFilter.project.name"];
          created_at?: parameters["rowFilter.project.created_at"];
          api_key?: parameters["rowFilter.project.api_key"];
          created_by_user_id?: parameters["rowFilter.project.created_by_user_id"];
          base_language_code?: parameters["rowFilter.project.base_language_code"];
        };
        body: {
          /** project */
          project?: definitions["project"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/project_member": {
    get: {
      parameters: {
        query: {
          project_id?: parameters["rowFilter.project_member.project_id"];
          user_id?: parameters["rowFilter.project_member.user_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["project_member"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** project_member */
          project_member?: definitions["project_member"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          project_id?: parameters["rowFilter.project_member.project_id"];
          user_id?: parameters["rowFilter.project_member.user_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          project_id?: parameters["rowFilter.project_member.project_id"];
          user_id?: parameters["rowFilter.project_member.user_id"];
        };
        body: {
          /** project_member */
          project_member?: definitions["project_member"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/user": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.user.id"];
          email?: parameters["rowFilter.user.email"];
          created_at?: parameters["rowFilter.user.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["user"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** user */
          user?: definitions["user"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.user.id"];
          email?: parameters["rowFilter.user.email"];
          created_at?: parameters["rowFilter.user.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.user.id"];
          email?: parameters["rowFilter.user.email"];
          created_at?: parameters["rowFilter.user.created_at"];
        };
        body: {
          /** user */
          user?: definitions["user"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rpc/get_user_id_from_email": {
    post: {
      parameters: {
        body: {
          args: {
            /** Format: text */
            email: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/handle_insert_user": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/handle_insert_project": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/is_member_of_project": {
    post: {
      parameters: {
        body: {
          args: {
            /** Format: uuid */
            project_id: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
}

export interface definitions {
  _prisma_migrations: {
    /**
     * Format: character varying
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** Format: character varying */
    checksum: string;
    /** Format: timestamp with time zone */
    finished_at?: string;
    /** Format: character varying */
    migration_name: string;
    /** Format: text */
    logs?: string;
    /** Format: timestamp with time zone */
    rolled_back_at?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    started_at: string;
    /** Format: integer */
    applied_steps_count: number;
  };
  language: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `project.id`.<fk table='project' column='id'/>
     */
    project_id: string;
    /** Format: text */
    file: string;
    /**
     * Format: public.iso_639_1
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    code:
      | "ab"
      | "aa"
      | "af"
      | "ak"
      | "sq"
      | "am"
      | "ar"
      | "an"
      | "hy"
      | "as"
      | "av"
      | "ae"
      | "ay"
      | "az"
      | "bm"
      | "ba"
      | "eu"
      | "be"
      | "bn"
      | "bh"
      | "bi"
      | "bs"
      | "br"
      | "bg"
      | "my"
      | "ca"
      | "km"
      | "ch"
      | "ce"
      | "ny"
      | "zh"
      | "cu"
      | "cv"
      | "kw"
      | "co"
      | "cr"
      | "hr"
      | "cs"
      | "da"
      | "dv"
      | "nl"
      | "dz"
      | "en"
      | "eo"
      | "et"
      | "ee"
      | "fo"
      | "fj"
      | "fi"
      | "fr"
      | "ff"
      | "gd"
      | "gl"
      | "lg"
      | "ka"
      | "de"
      | "ki"
      | "el"
      | "kl"
      | "gn"
      | "gu"
      | "ht"
      | "ha"
      | "he"
      | "hz"
      | "hi"
      | "ho"
      | "hu"
      | "is"
      | "io"
      | "ig"
      | "id"
      | "ia"
      | "ie"
      | "iu"
      | "ik"
      | "ga"
      | "it"
      | "ja"
      | "jv"
      | "kn"
      | "kr"
      | "ks"
      | "kk"
      | "rw"
      | "kv"
      | "kg"
      | "ko"
      | "kj"
      | "ku"
      | "ky"
      | "lo"
      | "la"
      | "lv"
      | "lb"
      | "li"
      | "ln"
      | "lt"
      | "lu"
      | "mk"
      | "mg"
      | "ms"
      | "ml"
      | "mt"
      | "gv"
      | "mi"
      | "mr"
      | "mh"
      | "ro"
      | "mn"
      | "na"
      | "nv"
      | "nd"
      | "ng"
      | "ne"
      | "se"
      | "no"
      | "nb"
      | "nn"
      | "ii"
      | "oc"
      | "oj"
      | "or"
      | "om"
      | "os"
      | "pi"
      | "pa"
      | "ps"
      | "fa"
      | "pl"
      | "pt"
      | "qu"
      | "rm"
      | "rn"
      | "ru"
      | "sm"
      | "sg"
      | "sa"
      | "sc"
      | "sr"
      | "sn"
      | "sd"
      | "si"
      | "sk"
      | "sl"
      | "so"
      | "st"
      | "nr"
      | "es"
      | "su"
      | "sw"
      | "ss"
      | "sv"
      | "tl"
      | "ty"
      | "tg"
      | "ta"
      | "tt"
      | "te"
      | "th"
      | "bo"
      | "ti"
      | "to"
      | "ts"
      | "tn"
      | "tr"
      | "tk"
      | "tw"
      | "ug"
      | "uk"
      | "ur"
      | "uz"
      | "ve"
      | "vi"
      | "vo"
      | "wa"
      | "cy"
      | "fy"
      | "wo"
      | "xh"
      | "yi"
      | "yo"
      | "za"
      | "zu";
  };
  project: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default gen_random_uuid()
     */
    id: string;
    /** Format: text */
    name: string;
    /**
     * Format: timestamp without time zone
     * @default CURRENT_TIMESTAMP
     */
    created_at: string;
    /**
     * Format: uuid
     * @default gen_random_uuid()
     */
    api_key: string;
    /** Format: uuid */
    created_by_user_id: string;
    /** Format: public.iso_639_1 */
    base_language_code:
      | "ab"
      | "aa"
      | "af"
      | "ak"
      | "sq"
      | "am"
      | "ar"
      | "an"
      | "hy"
      | "as"
      | "av"
      | "ae"
      | "ay"
      | "az"
      | "bm"
      | "ba"
      | "eu"
      | "be"
      | "bn"
      | "bh"
      | "bi"
      | "bs"
      | "br"
      | "bg"
      | "my"
      | "ca"
      | "km"
      | "ch"
      | "ce"
      | "ny"
      | "zh"
      | "cu"
      | "cv"
      | "kw"
      | "co"
      | "cr"
      | "hr"
      | "cs"
      | "da"
      | "dv"
      | "nl"
      | "dz"
      | "en"
      | "eo"
      | "et"
      | "ee"
      | "fo"
      | "fj"
      | "fi"
      | "fr"
      | "ff"
      | "gd"
      | "gl"
      | "lg"
      | "ka"
      | "de"
      | "ki"
      | "el"
      | "kl"
      | "gn"
      | "gu"
      | "ht"
      | "ha"
      | "he"
      | "hz"
      | "hi"
      | "ho"
      | "hu"
      | "is"
      | "io"
      | "ig"
      | "id"
      | "ia"
      | "ie"
      | "iu"
      | "ik"
      | "ga"
      | "it"
      | "ja"
      | "jv"
      | "kn"
      | "kr"
      | "ks"
      | "kk"
      | "rw"
      | "kv"
      | "kg"
      | "ko"
      | "kj"
      | "ku"
      | "ky"
      | "lo"
      | "la"
      | "lv"
      | "lb"
      | "li"
      | "ln"
      | "lt"
      | "lu"
      | "mk"
      | "mg"
      | "ms"
      | "ml"
      | "mt"
      | "gv"
      | "mi"
      | "mr"
      | "mh"
      | "ro"
      | "mn"
      | "na"
      | "nv"
      | "nd"
      | "ng"
      | "ne"
      | "se"
      | "no"
      | "nb"
      | "nn"
      | "ii"
      | "oc"
      | "oj"
      | "or"
      | "om"
      | "os"
      | "pi"
      | "pa"
      | "ps"
      | "fa"
      | "pl"
      | "pt"
      | "qu"
      | "rm"
      | "rn"
      | "ru"
      | "sm"
      | "sg"
      | "sa"
      | "sc"
      | "sr"
      | "sn"
      | "sd"
      | "si"
      | "sk"
      | "sl"
      | "so"
      | "st"
      | "nr"
      | "es"
      | "su"
      | "sw"
      | "ss"
      | "sv"
      | "tl"
      | "ty"
      | "tg"
      | "ta"
      | "tt"
      | "te"
      | "th"
      | "bo"
      | "ti"
      | "to"
      | "ts"
      | "tn"
      | "tr"
      | "tk"
      | "tw"
      | "ug"
      | "uk"
      | "ur"
      | "uz"
      | "ve"
      | "vi"
      | "vo"
      | "wa"
      | "cy"
      | "fy"
      | "wo"
      | "xh"
      | "yi"
      | "yo"
      | "za"
      | "zu";
  };
  project_member: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `project.id`.<fk table='project' column='id'/>
     */
    project_id: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `user.id`.<fk table='user' column='id'/>
     */
    user_id: string;
  };
  user: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** Format: text */
    email: string;
    /**
     * Format: timestamp without time zone
     * @default CURRENT_TIMESTAMP
     */
    created_at: string;
  };
}

export interface parameters {
  /** @description Preference */
  preferParams: "params=single-object";
  /** @description Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** @description Preference */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description _prisma_migrations */
  "body._prisma_migrations": definitions["_prisma_migrations"];
  /** Format: character varying */
  "rowFilter._prisma_migrations.id": string;
  /** Format: character varying */
  "rowFilter._prisma_migrations.checksum": string;
  /** Format: timestamp with time zone */
  "rowFilter._prisma_migrations.finished_at": string;
  /** Format: character varying */
  "rowFilter._prisma_migrations.migration_name": string;
  /** Format: text */
  "rowFilter._prisma_migrations.logs": string;
  /** Format: timestamp with time zone */
  "rowFilter._prisma_migrations.rolled_back_at": string;
  /** Format: timestamp with time zone */
  "rowFilter._prisma_migrations.started_at": string;
  /** Format: integer */
  "rowFilter._prisma_migrations.applied_steps_count": string;
  /** @description language */
  "body.language": definitions["language"];
  /** Format: uuid */
  "rowFilter.language.project_id": string;
  /** Format: text */
  "rowFilter.language.file": string;
  /** Format: public.iso_639_1 */
  "rowFilter.language.code": string;
  /** @description project */
  "body.project": definitions["project"];
  /** Format: uuid */
  "rowFilter.project.id": string;
  /** Format: text */
  "rowFilter.project.name": string;
  /** Format: timestamp without time zone */
  "rowFilter.project.created_at": string;
  /** Format: uuid */
  "rowFilter.project.api_key": string;
  /** Format: uuid */
  "rowFilter.project.created_by_user_id": string;
  /** Format: public.iso_639_1 */
  "rowFilter.project.base_language_code": string;
  /** @description project_member */
  "body.project_member": definitions["project_member"];
  /** Format: uuid */
  "rowFilter.project_member.project_id": string;
  /** Format: uuid */
  "rowFilter.project_member.user_id": string;
  /** @description user */
  "body.user": definitions["user"];
  /** Format: uuid */
  "rowFilter.user.id": string;
  /** Format: text */
  "rowFilter.user.email": string;
  /** Format: timestamp without time zone */
  "rowFilter.user.created_at": string;
}

export interface operations {}

export interface external {}
