//! Do not edit this file manually. It is automatically generated based on the contents of the registry.json file.

import type { MarketplaceManifest } from "@inlang/marketplace-manifest"
export const registry: MarketplaceManifest[] = []
