packages:
  - inlang/packages/**/*
  - lix/packages/**/*
  - '!inlang/packages/parrot-figma'
  - '!inlang/packages/fink'
  - '!packages/csv-app'
  - '!packages/lix/file-manager'
  - '!packages/lix/host'
  - '!inlang/packages/paraglide/paraglide-js/examples/next-js-ssg'
  - '!inlang/packages/paraglide/paraglide-js/examples/next-js-ssr'
  - '!**/*/dist'
  - '!inlang/packages/website/dist/**'
  - packages/**/*
  - packages/*/example
  - packages/*/examples/*
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
