export { createObjectStoreFs } from "./objectStoreFs.js"
export { default as createMappedObjectStore } from "./createMappedObjectStore.js"
export { default as initMappedObjectStore } from "./initMappedObjectStore.js"
export { default as createRemoteMappedObjectStore } from "./createRemoteMappedObjectStore.js"
export { default as resolveRemoteRef } from "./remote/resolveRemoteRef.js"
export type { ObjectStoreFilesystem } from "./types.js"
