import fs from "node:fs/promises"

/**
 * @typedef {Object} ModuleMetaData
 * @property {string} id
 * @property {Record<string, string>} displayName
 * @property {Record<string, string>} description
 * @property {Record<string, string>} marketplace
 * @property {string[]} keywords
 * @property {string} icon
 * @property {string} linkToReadme
 * @property {string} publisherName
 * @property {string} publisherIcon
 */

async function main() {
	const registry = JSON.parse(await fs.readFile("./registry.json", "utf-8"))

	for (let module of registry.modules) {
		if (module.includes("@latest") || !module.includes("jsdelivr")) continue
		registry.modules[registry.modules.indexOf(module)] = getLatestVersion(module)
	}

	const moduleItems = await getMetaData(registry.modules)

	const items = [...registry.apps, ...moduleItems]

	await fs.writeFile(
		"./src/registry.ts",
		`//! Do not edit this file manually. It is automatically generated based on the contents of the registry.json file.

		export const registry = ${JSON.stringify(items, undefined, "\t")}`,
	)
}

await main()

/**
 * @param {string} path
 * @returns {string}
 */
function getLatestVersion(module) {
	return (
		module.slice(0, module.lastIndexOf("@")) +
		"@latest" +
		module.slice(module.indexOf("/", module.lastIndexOf("@")))
	)
}

/**
 * @param {string[]} modules
 * @returns {Promise<ModuleMetaData[]>}
 */
async function getMetaData(modules) {
	const meta = []

	for (const module of modules) {
		const data = await import(module)
		const type = Object.keys(data.default)[0]

		for (const item of data.default[type]) {
			if (
				!item.meta.marketplace ||
				!item.meta.marketplace.keywords ||
				!item.meta.marketplace.icon ||
				!item.meta.marketplace.linkToReadme
			) {
				console.warn(`Module ${item.meta.id} has no marketplace metadata.`)
				continue
			}
			data.default[type].length > 1
				? meta.push({
						...item.meta,
						marketplace: {
							...item.meta.marketplace,
							bundle: data.default[type].length,
						},
				  })
				: meta.push(item.meta)
		}
	}

	return meta
}
