import type { Resource } from "@inlang/core/ast"
import consola, { Consola } from "consola"

/**
 * The logger that is used throughout the CLI.
 *
 * API -> https://www.npmjs.com/package/consola
 *
 * @example
 *   log.success("Success")
 */
export const log = consola as unknown as Consola

/**
 * Counts the number of messages per language.
 *
 * @param resource The resource to count the messages for.
 * @returns A record with the language as key and the number of messages as value.
 *
 */
export const countMessagesPerLanguage = (resource: Resource[]): Record<string, number> => {
	const counts: Record<string, number> = {}

	for (const { languageTag, body } of resource) {
		const language = languageTag.name

		if (!counts[language]) {
			counts[language] = 0
		}

		counts[language] += body.length
	}

	return counts
}

/**
 * Get emoji flag for a country code.
 *
 * @param countryCode The country code to get the flag for.
 * @returns The emoji flag.
 *
 */
export const getFlag = (countryCode: string) => {
	const cc = countryCode.toUpperCase()
	if (cc == "AD") return "🇦🇩"
	if (cc == "AE") return "🇦🇪"
	if (cc == "AF") return "🇦🇫"
	if (cc == "AG") return "🇦🇬"
	if (cc == "AI") return "🇦🇮"
	if (cc == "AL") return "🇦🇱"
	if (cc == "AM") return "🇦🇲"
	if (cc == "AO") return "🇦🇴"
	if (cc == "AQ") return "🇦🇶"
	if (cc == "AR") return "🇦🇷"
	if (cc == "AS") return "🇦🇸"
	if (cc == "AT") return "🇦🇹"
	if (cc == "AU") return "🇦🇺"
	if (cc == "AW") return "🇦🇼"
	if (cc == "AX") return "🇦🇽"
	if (cc == "AZ") return "🇦🇿"
	if (cc == "BA") return "🇧🇦"
	if (cc == "BB") return "🇧🇧"
	if (cc == "BD") return "🇧🇩"
	if (cc == "BE") return "🇧🇪"
	if (cc == "BF") return "🇧🇫"
	if (cc == "BG") return "🇧🇬"
	if (cc == "BH") return "🇧🇭"
	if (cc == "BI") return "🇧🇮"
	if (cc == "BJ") return "🇧🇯"
	if (cc == "BL") return "🇧🇱"
	if (cc == "BM") return "🇧🇲"
	if (cc == "BN") return "🇧🇳"
	if (cc == "BO") return "🇧🇴"
	if (cc == "BQ") return "🇧🇶"
	if (cc == "BR") return "🇧🇷"
	if (cc == "BS") return "🇧🇸"
	if (cc == "BT") return "🇧🇹"
	if (cc == "BV") return "🇧🇻"
	if (cc == "BW") return "🇧🇼"
	if (cc == "BY") return "🇧🇾"
	if (cc == "BZ") return "🇧🇿"
	if (cc == "CA") return "🇨🇦"
	if (cc == "CC") return "🇨🇨"
	if (cc == "CD") return "🇨🇩"
	if (cc == "CF") return "🇨🇫"
	if (cc == "CG") return "🇨🇬"
	if (cc == "CH") return "🇨🇭"
	if (cc == "CI") return "🇨🇮"
	if (cc == "CK") return "🇨🇰"
	if (cc == "CL") return "🇨🇱"
	if (cc == "CM") return "🇨🇲"
	if (cc == "CN") return "🇨🇳"
	if (cc == "CO") return "🇨🇴"
	if (cc == "CR") return "🇨🇷"
	if (cc == "CU") return "🇨🇺"
	if (cc == "CV") return "🇨🇻"
	if (cc == "CW") return "🇨🇼"
	if (cc == "CX") return "🇨🇽"
	if (cc == "CY") return "🇨🇾"
	if (cc == "CZ") return "🇨🇿"
	if (cc == "DE") return "🇩🇪"
	if (cc == "DJ") return "🇩🇯"
	if (cc == "DK") return "🇩🇰"
	if (cc == "DM") return "🇩🇲"
	if (cc == "DO") return "🇩🇴"
	if (cc == "DZ") return "🇩🇿"
	if (cc == "EC") return "🇪🇨"
	if (cc == "EE") return "🇪🇪"
	if (cc == "EG") return "🇪🇬"
	if (cc == "EH") return "🇪🇭"
	if (cc == "ER") return "🇪🇷"
	if (cc == "ES") return "🇪🇸"
	if (cc == "ET") return "🇪🇹"
	if (cc == "FI") return "🇫🇮"
	if (cc == "FJ") return "🇫🇯"
	if (cc == "FK") return "🇫🇰"
	if (cc == "FM") return "🇫🇲"
	if (cc == "FO") return "🇫🇴"
	if (cc == "FR") return "🇫🇷"
	if (cc == "GA") return "🇬🇦"
	if (cc == "GB") return "🇬🇧"
	if (cc == "GD") return "🇬🇩"
	if (cc == "GE") return "🇬🇪"
	if (cc == "GF") return "🇬🇫"
	if (cc == "GG") return "🇬🇬"
	if (cc == "GH") return "🇬🇭"
	if (cc == "GI") return "🇬🇮"
	if (cc == "GL") return "🇬🇱"
	if (cc == "GM") return "🇬🇲"
	if (cc == "GN") return "🇬🇳"
	if (cc == "GP") return "🇬🇵"
	if (cc == "GQ") return "🇬🇶"
	if (cc == "GR") return "🇬🇷"
	if (cc == "GS") return "🇬🇸"
	if (cc == "GT") return "🇬🇹"
	if (cc == "GU") return "🇬🇺"
	if (cc == "GW") return "🇬🇼"
	if (cc == "GY") return "🇬🇾"
	if (cc == "HK") return "🇭🇰"
	if (cc == "HM") return "🇭🇲"
	if (cc == "HN") return "🇭🇳"
	if (cc == "HR") return "🇭🇷"
	if (cc == "HT") return "🇭🇹"
	if (cc == "HU") return "🇭🇺"
	if (cc == "ID") return "🇮🇩"
	if (cc == "IE") return "🇮🇪"
	if (cc == "IL") return "🇮🇱"
	if (cc == "IM") return "🇮🇲"
	if (cc == "IN") return "🇮🇳"
	if (cc == "IO") return "🇮🇴"
	if (cc == "IQ") return "🇮🇶"
	if (cc == "IR") return "🇮🇷"
	if (cc == "IS") return "🇮🇸"
	if (cc == "IT") return "🇮🇹"
	if (cc == "JE") return "🇯🇪"
	if (cc == "JM") return "🇯🇲"
	if (cc == "JO") return "🇯🇴"
	if (cc == "JP") return "🇯🇵"
	if (cc == "KE") return "🇰🇪"
	if (cc == "KG") return "🇰🇬"
	if (cc == "KH") return "🇰🇭"
	if (cc == "KI") return "🇰🇮"
	if (cc == "KM") return "🇰🇲"
	if (cc == "KN") return "🇰🇳"
	if (cc == "KP") return "🇰🇵"
	if (cc == "KR") return "🇰🇷"
	if (cc == "KW") return "🇰🇼"
	if (cc == "KY") return "🇰🇾"
	if (cc == "KZ") return "🇰🇿"
	if (cc == "LA") return "🇱🇦"
	if (cc == "LB") return "🇱🇧"
	if (cc == "LC") return "🇱🇨"
	if (cc == "LI") return "🇱🇮"
	if (cc == "LK") return "🇱🇰"
	if (cc == "LR") return "🇱🇷"
	if (cc == "LS") return "🇱🇸"
	if (cc == "LT") return "🇱🇹"
	if (cc == "LU") return "🇱🇺"
	if (cc == "LV") return "🇱🇻"
	if (cc == "LY") return "🇱🇾"
	if (cc == "MA") return "🇲🇦"
	if (cc == "MC") return "🇲🇨"
	if (cc == "MD") return "🇲🇩"
	if (cc == "ME") return "🇲🇪"
	if (cc == "MF") return "🇲🇫"
	if (cc == "MG") return "🇲🇬"
	if (cc == "MH") return "🇲🇭"
	if (cc == "MK") return "🇲🇰"
	if (cc == "ML") return "🇲🇱"
	if (cc == "MM") return "🇲🇲"
	if (cc == "MN") return "🇲🇳"
	if (cc == "MO") return "🇲🇴"
	if (cc == "MP") return "🇲🇵"
	if (cc == "MQ") return "🇲🇶"
	if (cc == "MR") return "🇲🇷"
	if (cc == "MS") return "🇲🇸"
	if (cc == "MT") return "🇲🇹"
	if (cc == "MU") return "🇲🇺"
	if (cc == "MV") return "🇲🇻"
	if (cc == "MW") return "🇲🇼"
	if (cc == "MX") return "🇲🇽"
	if (cc == "MY") return "🇲🇾"
	if (cc == "MZ") return "🇲🇿"
	if (cc == "NA") return "🇳🇦"
	if (cc == "NC") return "🇳🇨"
	if (cc == "NE") return "🇳🇪"
	if (cc == "NF") return "🇳🇫"
	if (cc == "NG") return "🇳🇬"
	if (cc == "NI") return "🇳🇮"
	if (cc == "NL") return "🇳🇱"
	if (cc == "NO") return "🇳🇴"
	if (cc == "NP") return "🇳🇵"
	if (cc == "NR") return "🇳🇷"
	if (cc == "NU") return "🇳🇺"
	if (cc == "NZ") return "🇳🇿"
	if (cc == "OM") return "🇴🇲"
	if (cc == "PA") return "🇵🇦"
	if (cc == "PE") return "🇵🇪"
	if (cc == "PF") return "🇵🇫"
	if (cc == "PG") return "🇵🇬"
	if (cc == "PH") return "🇵🇭"
	if (cc == "PK") return "🇵🇰"
	if (cc == "PL") return "🇵🇱"
	if (cc == "PM") return "🇵🇲"
	if (cc == "PN") return "🇵🇳"
	if (cc == "PR") return "🇵🇷"
	if (cc == "PS") return "🇵🇸"
	if (cc == "PT") return "🇵🇹"
	if (cc == "PW") return "🇵🇼"
	if (cc == "PY") return "🇵🇾"
	if (cc == "QA") return "🇶🇦"
	if (cc == "RE") return "🇷🇪"
	if (cc == "RO") return "🇷🇴"
	if (cc == "RS") return "🇷🇸"
	if (cc == "RU") return "🇷🇺"
	if (cc == "RW") return "🇷🇼"
	if (cc == "SA") return "🇸🇦"
	if (cc == "SB") return "🇸🇧"
	if (cc == "SC") return "🇸🇨"
	if (cc == "SD") return "🇸🇩"
	if (cc == "SE") return "🇸🇪"
	if (cc == "SG") return "🇸🇬"
	if (cc == "SH") return "🇸🇭"
	if (cc == "SI") return "🇸🇮"
	if (cc == "SJ") return "🇸🇯"
	if (cc == "SK") return "🇸🇰"
	if (cc == "SL") return "🇸🇱"
	if (cc == "SM") return "🇸🇲"
	if (cc == "SN") return "🇸🇳"
	if (cc == "SO") return "🇸🇴"
	if (cc == "SR") return "🇸🇷"
	if (cc == "SS") return "🇸🇸"
	if (cc == "ST") return "🇸🇹"
	if (cc == "SV") return "🇸🇻"
	if (cc == "SX") return "🇸🇽"
	if (cc == "SY") return "🇸🇾"
	if (cc == "SZ") return "🇸🇿"
	if (cc == "TC") return "🇹🇨"
	if (cc == "TD") return "🇹🇩"
	if (cc == "TF") return "🇹🇫"
	if (cc == "TG") return "🇹🇬"
	if (cc == "TH") return "🇹🇭"
	if (cc == "TJ") return "🇹🇯"
	if (cc == "TK") return "🇹🇰"
	if (cc == "TL") return "🇹🇱"
	if (cc == "TM") return "🇹🇲"
	if (cc == "TN") return "🇹🇳"
	if (cc == "TO") return "🇹🇴"
	if (cc == "TR") return "🇹🇷"
	if (cc == "TT") return "🇹🇹"
	if (cc == "TV") return "🇹🇻"
	if (cc == "TW") return "🇹🇼"
	if (cc == "TZ") return "🇹🇿"
	if (cc == "UA") return "🇺🇦"
	if (cc == "UG") return "🇺🇬"
	if (cc == "UM") return "🇺🇲"
	if (cc == "US") return "🇺🇸"
	if (cc == "UY") return "🇺🇾"
	if (cc == "UZ") return "🇺🇿"
	if (cc == "VA") return "🇻🇦"
	if (cc == "VC") return "🇻🇨"
	if (cc == "VE") return "🇻🇪"
	if (cc == "VG") return "🇻🇬"
	if (cc == "VI") return "🇻🇮"
	if (cc == "VN") return "🇻🇳"
	if (cc == "VU") return "🇻🇺"
	if (cc == "WF") return "🇼🇫"
	if (cc == "WS") return "🇼🇸"
	if (cc == "XK") return "🇽🇰"
	if (cc == "YE") return "🇾🇪"
	if (cc == "YT") return "🇾🇹"
	if (cc == "ZA") return "🇿🇦"
	if (cc == "ZM") return "🇿🇲"
	if (cc == "ZW") return "🇿🇼"
	return "🏳"
}
