//! Do not edit this file manually. It is automatically generated based on the contents of the registry.json file.

export const registry = [
	{
		meta: {
			id: "inlang.app.webEditor",
			displayName: {
				en: "Web Editor",
			},
			description: {
				en: "The inlang web editor is a simple and easy-to-use no-code tool to manage your translations.",
			},
			marketplace: {
				icon: "https://inlang.com/favicon/safari-pinned-tab.svg",
				linkToReadme: {
					en: "https://github.com/inlang/inlang/blob/main/source-code/website/src/pages/editor/README.md",
				},
				keywords: ["web", "editor", "no-code"],
				publisherName: "inlang",
				publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
			},
		},
		type: "app",
		linkToApp: "/editor",
	},
	{
		meta: {
			id: "inlang.app.cli",
			displayName: {
				en: "CLI",
			},
			description: {
				en: "@inlang/cli is a command line interface (CLI) tool that allows you to interact with the Inlang infrastructure.",
			},
			marketplace: {
				icon: "https://inlang.com/favicon/safari-pinned-tab.svg",
				linkToReadme: {
					en: "https://github.com/inlang/inlang/blob/main/source-code/cli/README.md",
				},
				keywords: ["cli", "automation"],
				publisherName: "inlang",
				publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
			},
		},
		type: "app",
	},
	{
		meta: {
			id: "inlang.app.ideExtension",
			displayName: {
				en: "IDE Extension",
			},
			description: {
				en: "The VS Code extension provides seamless integration of Inlang's globalization infrastructure into Visual Studio Code.",
			},
			marketplace: {
				icon: "https://inlang.com/favicon/safari-pinned-tab.svg",
				linkToReadme: {
					en: "https://github.com/inlang/inlang/blob/main/source-code/ide-extension/README.md",
				},
				keywords: ["vscode", "efficiency", "extension"],
				publisherName: "inlang",
				publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
			},
		},
		type: "app",
		linkToApp: "vscode:extension/inlang.vs-code-extension",
	},
	{
		meta: {
			id: "inlang.app.badge",
			displayName: {
				en: "Badge",
			},
			description: {
				en: "Create a badge to show how many translations are missing in your project.",
			},
			marketplace: {
				icon: "https://inlang.com/favicon/safari-pinned-tab.svg",
				linkToReadme: {
					en: "https://github.com/inlang/inlang/blob/main/source-code/badge/README.md",
				},
				keywords: ["badge", "embed"],
				publisherName: "inlang",
				publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
			},
		},
		type: "app",
	},
	{
		meta: {
			id: "inlang.library.paraglideJS",
			displayName: {
				en: "ParaglideJS",
			},
			description: {
				en: "Easy to setup and fully customizable SDK to globalize your web app with inlang.",
			},
			marketplace: {
				icon: "https://emojis.wiki/thumbs/emojis/parachute.webp",
				linkToReadme: {
					en: "https://github.com/inlang/inlang/blob/armageddon/source-code/paraglide/README.md",
				},
				keywords: ["paraglide", "js", "sdk"],
				publisherName: "inlang",
				publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
			},
		},
		type: "library",
	},
	{
		meta: {
			id: "inlang.library.languageTag",
			displayName: {
				en: "Language Tag",
			},
			description: {
				en: "BCP-47 language tags types and validators.",
			},
			marketplace: {
				icon: "https://inlang.com/favicon/safari-pinned-tab.svg",
				linkToReadme: {
					en: "https://github.com/inlang/inlang/blob/armageddon/source-code/core/language-tag/README.md",
				},
				keywords: ["language", "tags"],
				publisherName: "inlang",
				publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
			},
		},
		type: "library",
	},
]
