//! Do not edit this file manually. It is automatically generated based on the contents of the registry.json file.

export const registry = [
	{
		type: "app",
		icon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		displayName: {
			en: "CLI",
		},
		description: {
			en: "Official inlang CLI",
		},
		linkToReadme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/cli/README.md",
		},
		keywords: ["cli", "commands"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
	},
	{
		type: "app",
		icon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		displayName: {
			en: "Badge",
		},
		description: {
			en: "Badge showing missing messages and more",
		},
		linkToReadme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/badge/README.md",
		},
		keywords: ["badge"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
	},
	{
		type: "app",
		icon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		displayName: {
			en: "Web Editor",
		},
		description: {
			en: "inlang's Web Editor",
		},
		linkToReadme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/editor/README.md",
		},
		keywords: ["web", "editor", "visual"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
		linkToApp: "/editor",
	},
	{
		type: "app",
		icon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		displayName: {
			en: "IDE Extension",
		},
		description: {
			en: "IDE Extension for inlang projects",
		},
		linkToReadme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/ide-extension/README.md",
		},
		keywords: ["ide", "extension", "vscode"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
	},
	{
		type: "plugin",
		icon: "https://github.com/inlang/inlang/blob/main/source-code/plugins/json/assets/icon.png?raw=true",
		displayName: {
			en: "Plugin JSON",
		},
		description: {
			en: "JSON plugin for inlang",
		},
		linkToReadme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/plugins/json/README.md",
		},
		keywords: ["json", "generic"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
		module: "../../plugins/json/dist/index.js",
	},
	{
		type: "plugin",
		icon: "https://github.com/inlang/inlang/blob/main/source-code/plugins/i18next/assets/icon.png?raw=true",
		displayName: {
			en: "i18next",
		},
		description: {
			en: "i18next plugin for inlang",
		},
		linkToReadme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/plugins/json/README.md",
		},
		keywords: ["i18next", "react", "nextjs"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
		module: "../../plugins/i18next/dist/index.js",
	},
	{
		type: "lintRule",
		icon: "https://raw.githubusercontent.com/inlang/inlang/main/source-code/plugins/standard-lint-rules/assets/icon.png",
		displayName: {
			en: "Empty Pattern",
		},
		description: {
			en: "Checks for empty pattern in a language tag. If a message exists in the reference resource but the pattern in a target resource is empty, it is likely that the message has not been translated yet.",
		},
		linkToReadme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/plugins/standard-lint-rules/README.md",
		},
		keywords: ["lint rule", "empty pattern"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
		module: "../../plugins/emptyPattern/emptyPattern.js",
	},
	{
		type: "lintRule",
		icon: "https://raw.githubusercontent.com/inlang/inlang/main/source-code/plugins/standard-lint-rules/assets/icon.png",
		displayName: {
			en: "Identical Pattern",
		},
		description: {
			en: "Checks for identical patterns in different languages.  A message with identical wording in multiple languages can indicate that the translations are redundant or can be combined into a single message to reduce translation effort.",
		},
		linkToReadme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/plugins/standard-lint-rules/README.md",
		},
		keywords: ["lint rule", "itentical pattern"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
		module: "../../plugins/identicalPattern/identicalPattern.js",
	},
	{
		type: "lintRule",
		icon: "https://raw.githubusercontent.com/inlang/inlang/main/source-code/plugins/standard-lint-rules/assets/icon.png",
		displayName: {
			en: "Message without Source",
		},
		description: {
			en: "Checks for likely outdated messages.  A message with a missing source is usually an indication that the message (id) is no longer used in source code, but messages have not been updated accordingly.",
		},
		linkToReadme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/plugins/standard-lint-rules/README.md",
		},
		keywords: ["lint rule", "source"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
		module: "../../plugins/messageWithoutSource/messageWithoutSource.js",
	},
	{
		type: "lintRule",
		icon: "https://raw.githubusercontent.com/inlang/inlang/main/source-code/plugins/standard-lint-rules/assets/icon.png",
		displayName: {
			en: "Missing Translation",
		},
		description: {
			en: "Checks for missing variants for a specific languageTag.  If a variant exists for the sourceLanguageTag but is missing for a listed languageTag, it is likely that the message has not been translated for this languageTag yet.",
		},
		linkToReadme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/plugins/standard-lint-rules/README.md",
		},
		keywords: ["lint rule", "missing"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
		module: "../../plugins/missingTranslation/missingTranslation.js",
	},
]
