//! Do not edit this file manually. It is automatically generated based on the contents of the registry.json file.

export const registry = [
	{
		type: "app",
		icon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		displayName: {
			en: "CLI",
		},
		description: {
			en: "Official inlang CLI",
		},
		linkToReadme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/cli/README.md",
		},
		keywords: ["cli", "commands"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
	},
	{
		type: "app",
		icon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		displayName: {
			en: "Badge",
		},
		description: {
			en: "Badge showing missing messages and more",
		},
		linkToReadme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/badge/README.md",
		},
		keywords: ["badge"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
	},
	{
		type: "app",
		icon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		displayName: {
			en: "Web Editor",
		},
		description: {
			en: "inlang's Web Editor",
		},
		linkToReadme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/editor/README.md",
		},
		keywords: ["web", "editor", "visual"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
	},
	{
		type: "app",
		icon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		displayName: {
			en: "IDE Extension",
		},
		description: {
			en: "IDE Extension for inlang projects",
		},
		linkToReadme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/ide-extension/README.md",
		},
		keywords: ["ide", "extension", "vscode"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
	},
	{
		type: "plugin",
		icon: "https://github.com/inlang/inlang/blob/main/source-code/plugins/json/assets/icon.png?raw=true",
		displayName: {
			en: "Plugin JSON",
		},
		description: {
			en: "JSON plugin for inlang",
		},
		linkToReadme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/plugins/json/README.md",
		},
		keywords: ["json", "generic"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
		module: "../../plugins/json/dist/index.js",
	},
	{
		type: "plugin",
		icon: "https://github.com/inlang/inlang/blob/main/source-code/plugins/i18next/assets/icon.png?raw=true",
		displayName: {
			en: "i18next",
		},
		description: {
			en: "i18next plugin for inlang",
		},
		linkToReadme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/plugins/json/README.md",
		},
		keywords: ["i18next", "react", "nextjs"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
		module: "../../plugins/i18next/dist/index.js",
	},
]
