//! Do not edit this file manually. It is automatically generated based on the contents of the registry.json file.

export const registry = [
	{
		type: "plugin",
		icon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		displayName: {
			en: "Plugin JSON",
		},
		description: {
			en: "JSON plugin for inlang",
		},
		linkToReadme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/plugins/json/README.md",
		},
		keywords: ["json", "generic"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
		module: "../../plugins/json/dist/index.js",
	},
]
