import fs from "node:fs/promises"

async function main() {
	const registry = JSON.parse(await fs.readFile("./registry.json", "utf-8"))
	/** @type {import("./src/schema.js").MarketplaceItem[]} */
	const items = [...registry.apps]

	for (let module of registry.modules) {
		// if (module.includes("jsdelivr") === false) {
		// 	throw new Error(
		// 		`Module ${module} is not hosted on jsdelivr. Please host it there and update the registry.json file.`,
		// 	)
		// }
		items.push(...(await getMarketplaceItems(module)))
	}

	await fs.writeFile(
		"./src/registry.ts",
		`//! Do not edit this file manually. It is automatically generated based on the contents of the registry.json file.

		export const registry = ${JSON.stringify(items, undefined, "\t")}`,
	)
}

await main()

// ToDo: Move to new install app
// /**
//  * @param {string} path
//  * @returns {string}
//  */
// function getLatestVersion(module) {
// 	return (
// 		module.slice(0, module.lastIndexOf("@")) +
// 		"@latest" +
// 		module.slice(module.indexOf("/", module.lastIndexOf("@")))
// 	)
// }

/**
 * @param {string} module
 * @returns {Promise<import("./src/schema.js").MarketplaceItem[]>}
 */
async function getMarketplaceItems(module) {
	const result = []

	/** @type {import("@inlang/module").InlangModule} */
	const inlangModule = await import(module)

	const exportedItems = [
		...(inlangModule.default.plugins ?? []),
		...(inlangModule.default.lintRules ?? []),
	]

	for (const item of exportedItems) {
		if (item.meta.marketplace === undefined) {
			throw Error(
				`Module ${item.meta.id} has no marketplace metadata. Remove it from the registry.`,
			)
		}
		result.push({
			meta: {
				...item.meta,
			},
			type: item.meta.id.split(".")[1],
			moduleItems: exportedItems.map((item) => item.meta.id),
			module,
		})
	}

	// @ts-ignore
	return result
}
