import { compileMessage } from "./compileMessage.js"
import dedent from "dedent"
import type { CompileFunction } from "../cli/types.js"

/**
 * Heads up for developers that a file is automatically generated.
 */
const thisIsACompiledFileComment = dedent`
/**
 * !This file is automatically generated by the inlang paraglide-js compiler!
 */
`

/**
 * Compiles an inlang project into the importable paraglide-js library.
 */
export const compile: CompileFunction = (args) => {
	const compiledMessages = args.messages.map(compileMessage).join("\n\n")

	return {
		// for unknown reasons, typescript needs dedicated .d.ts files and
		// the d.ts files cannot shadow the js files. Hence, the _ prefix.
		"runtime$.d.ts": `export * from "./runtime.js"`,
		"messages$.d.ts": `export * from "./messages.js"`,
		"messages.js": dedent`
${thisIsACompiledFileComment}

import { languageTag } from "./runtime.js"

${compiledMessages}
`,
		"runtime.js": dedent`
${thisIsACompiledFileComment}

/**
 * Callback function that is called whenever the language tag changes.
 * 
 * @type {((tag: typeof availableLanguageTags[number]) => void) | undefined}
 */ 
let _onSetLanguageTag

/**
 * The project's source language tag.
 */
export const sourceLanguageTag = "${args.settings.sourceLanguageTag}"

/**
 * The project's language tags.
 */
export const availableLanguageTags = /** @type {const} */ (${JSON.stringify(
			args.settings.languageTags
		)})

/**
 * Get current language tag.
 * 
 * @type {() => typeof availableLanguageTags[number]}
 */
export let languageTag = () => sourceLanguageTag

/**
 * Set the language tag.
 * 
 * @example 
 *   setLanguageTag("en")
 * 
 *   // passing a getter function also works. 
 *   // 
 *   // a getter function is useful for resolving a language tag 
 *   // from a context like React's context API or retrieving the language tag 
 *   // from a cookie.
 *   setLanguageTag(() => {
 *     return cookies.get("lang")
 *   }) 
 *
 * @param {typeof availableLanguageTags[number] | typeof languageTag} tag
 */
export const setLanguageTag = (tag) => {
	if (typeof tag === "function") {
		languageTag = tag
	} else {
		languageTag = () => tag
	}
	// call the callback function if it has been defined
	if (_onSetLanguageTag !== undefined) {
		_onSetLanguageTag(languageTag())
	}
}

/**
 * Set the \`onSetLanguageTag()\` callback function.
 *
 * The function can be used to trigger client-side side-effects such as 
 * making a new request to the server with the updated language tag, 
 * or re-rendering the UI on the client (SPA apps).  
 * 
 * - Don't use this function on the server (!).
 *   Triggering a side-effect is only useful on the client because a server-side
 *   environment doesn't need to re-render the UI. 
 *     
 * - The \`onSetLanguageTag()\` callback can only be defined once to avoid unexpected behavior.
 * 
 * @example
 *   // if you use inlang paraglide on the server, make sure to not call \`onSetLanguageTag()\` on the server
 *   if (isServer === false) {
 *     onSetLanguageTag((tag) => {
 *       // (for example) make a new request to the server with the updated language tag
 *       window.location.href = \`/\${tag}/\${window.location.pathname}\`
 *     })
 *   }
 *
 * @param {(tag: typeof availableLanguageTags[number]) => void} fn
 */
export const onSetLanguageTag = (fn) => {
	if (_onSetLanguageTag !== undefined) {
		throw new Error("@inlang/paraglide-js: The \`onSetLanguageTag()\` callback has already been defined.\\n\\nThe \`onSetLanguageTag()\` callback can only be defined once to avoid unexpected behavior.\\n\\n 1) Try searching for \`onSetLanguageTag()\` in your codebase for potential duplicated.\\n 2) If you use inlang paraglide on the server, make sure to not call \`onSetLanguageTag()\` as onSetLanguageTag is a client only API.")
	}
	_onSetLanguageTag = fn
}
`,
	}
}
