/**
 * MESSAGES.JS IS ALWAYS AUTOGENERATED BY THE PARAGLIDE COMPILER!
 * FOR TESTING PURPOSES, THIS IS A MANUALLY CREATED MESSAGES FILE.
 */

export const onlyText = () => ({
	en: "Only text",
	de: "Nur Text",
})

export const oneParam = /** @param {{ name: NonNullable<unknown> }} params */ (params) => ({
	en: `Hello ${params.name}!`,
	de: `Hallo ${params.name}!`,
})

export const multipleParams =
	/** @param {{ name: NonNullable<unknown>, count: NonNullable<unknown> }} params */ (params) => ({
		en: `Hello ${params.name}! You have ${params.count} messages.`,
		de: `Hallo ${params.name}! Du hast ${params.count} Nachrichten.`,
	})

export const withMultipleVariants =
	/** @param {{ name: NonNullable<unknown> , count: NonNullable<unknown> }} params */ (params) => ({
		selectorOrdering: ["gender", "guestOther"],
		en: [
			{
				match: { gender: "female", count: "1" },
				pattern: `Hello Ms. ${params.name}! You have one message.`,
			},
			{
				match: { gender: "male", count: "1" },
				pattern: `Hello Mr. ${params.name}! You have one message.`,
			},
			{
				match: { gender: "*", guestOther: "*" },
				pattern: `Hello ${params.name}! You have ${params.count} messages.`,
			},
		],
		de: [
			{
				match: { gender: "female", count: "1" },
				pattern: `Hallo Frau ${params.name}! Du hast eine Nachricht.`,
			},
			{
				match: { gender: "male", count: "1" },
				pattern: `Hallo Herr ${params.name}! Du hast eine Nachricht.`,
			},
			{
				match: { gender: "*", guestOther: "*" },
				pattern: `Hallo ${params.name}! Du hast ${params.count} Nachrichten.`,
			},
		],
	})
