name: Bug report
description: Something is not working as expected
title: '[bug] <title>'
labels:
   - 'type: bug'
body:
   - type: textarea
     id: bug-description
     attributes:
        label: Problem
        description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
        placeholder: Bug description
     validations:
        required: true
   - type: textarea
     id: fix-description
     attributes:
        label: Expected behavior
        description: A clear and concise description of what you expected to happen.
        placeholder: What did you expect to happen?
   - type: textarea
     id: reproduction
     attributes:
        label: Reproduction
        description: Please provide a description and/or a link to a repo that can reproduce the problem you ran into
        placeholder: |
           # 1. Go to '...'
           # 2. Click on '....'
           # 3. ...
     validations:
        required: true
   - type: textarea
     id: inlang-config-file
     attributes:
        label: '`inlang.config.js` file'
        description: Please include the contents of your `inlang.config.js` file
        render: JavaScript
     validations:
        required: true
   - type: textarea
     id: validate-config-output
     attributes:
        label: '`npx @inlang/cli@latest config validate` file'
        description: Please validate the config file with `npx @inlang/cli config validate` and include the output here
        render: sh
   - type: textarea
     id: other
     attributes:
        label: 'Other information'
        description: Do you have additional information that could help us fix the bug? Please include it here.
        placeholder: |
           # - Browser:
           # - Operating system:
           # - Screenshots ?
