// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType } from 'typesafe-i18n'
import type { LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'da'
	| 'de'
	| 'en'
	| 'fr'

export type Translation = {
	/**
	 * hi
	 */
	'test': string
	/**
	 * Learn React
	 */
	'learn': string
	/**
	 * Edit <code>src/App.js</code> and save to reload.
	 */
	'edit': string
	/**
	 * Welcome to the Inlang React example!
	 */
	'welcome': string
	/**
	 * The open-source translation management platform.
	 */
	'subtitle': string
	/**
	 * Try pressing one of these
	 */
	'press': string
	/**
	 * this is atest
	 */
	'asd': string
}

export type TranslationFunctions = {
	/**
	 * hi
	 */
	'test': () => LocalizedString
	/**
	 * Learn React
	 */
	'learn': () => LocalizedString
	/**
	 * Edit <code>src/App.js</code> and save to reload.
	 */
	'edit': () => LocalizedString
	/**
	 * Welcome to the Inlang React example!
	 */
	'welcome': () => LocalizedString
	/**
	 * The open-source translation management platform.
	 */
	'subtitle': () => LocalizedString
	/**
	 * Try pressing one of these
	 */
	'press': () => LocalizedString
	/**
	 * this is atest
	 */
	'asd': () => LocalizedString
}

export type Formatters = {}
