import type { Metadata } from "next";
import { getLocale, localizePath } from "../paraglide/runtime";
import ClientSideLocaleSwitch from "./ClientSideLocaleSwitch";
import ParaglideNextProvider from "../paraglide/adapter.provider";
import Link from "next/link";
import * as m from "../paraglide/messages.js";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ParaglideNextProvider>
			<html lang={getLocale()}>
				<body>
					<b>
						<p>{m.static_anchor_tags_info()}</p>
					</b>
					<div>
						<Link href={localizePath("/", { locale: "en" })}>
							{m.navigate_to_en()}
						</Link>
					</div>
					<div>
						<Link href={localizePath("/", { locale: "de" })}>
							{m.navigate_to_de()}
						</Link>
					</div>
					<b>
						<p>{m.programmatic_locale_switching_info()}</p>
					</b>
					<ClientSideLocaleSwitch />
					<hr />
					{children}
				</body>
			</html>
		</ParaglideNextProvider>
	);
}
