export { changeConflictInVersion } from "./change-conflict-in-version.js";
export { changeHasLabel } from "./change-has-label.js";
export { changeIsLeafInVersion } from "./change-is-leaf-in-version.js";
export { changeInVersion } from "./change-in-version.js";
export { changeIsLowestCommonAncestorOf } from "./change-is-lowest-common-ancestor-of.js";
export { changeSetHasLabel } from "./change-set-has-label.js";
export { changeSetIsAncestorOf } from "./change-set-is-ancestor-of.js";
export { changeSetIsDescendantOf } from "./change-set-is-descendant-of.js";
export { changeSetElementIsLeafOf } from "./change-set-element-is-leaf-of.js";
