//! Do not edit this file manually. It is automatically generated based on the contents of the registry.json file.

import type { MarketplaceManifest } from "@inlang/marketplace-manifest"
export const registry: MarketplaceManifest[] = [
	{
		id: "app.inlang.cli",
		icon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		displayName: {
			en: "inlang CLI",
		},
		description: {
			en: "Official inlang CLI",
		},
		readme: {
			en: "https://raw.githubusercontent.com/inlang/inlang/main/source-code/cli/README.md",
		},
		keywords: ["cli", "commands"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
	},
	{
		id: "lintRule.inlang.emptyPattern",
		icon: "https://raw.githubusercontent.com/inlang/inlang/main/source-code/plugins/standard-lint-rules/assets/icon.png",
		displayName: {
			en: "Empty Pattern",
		},
		description: {
			en: "Checks for empty pattern in a language tag. If a message exists in the reference resource but the pattern in a target resource is empty, it is likely that the message has not been translated yet.",
		},
		readme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/lint-rules/emptyPattern/README.md",
		},
		keywords: ["lint rule", "empty pattern"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
		module: "../../plugins/emptyPattern/emptyPattern.js",
	},
]
