//! Do not edit this file manually. It is automatically generated based on the contents of the registry.json file.

import type { MarketplaceManifest } from "@inlang/marketplace-manifest"
export const registry: MarketplaceManifest[] = [
	{
		id: "app.inlang.cli",
		icon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		coverImage:
			"https://cdn.jsdelivr.net/gh/inlang/monorepo@latest/inlang/assets/marketplace/cli-marketplace-cover.jpg",
		displayName: {
			en: "CLI",
		},
		description: {
			en: "Command line interface for inlang projects. Many commands and the possibility to do automation.",
		},
		tableOfContents: [
			{
				startpage: true,
				path: {
					en: "https://cdn.jsdelivr.net/gh/inlang/monorepo@main/inlang/source-code/cli/README.md",
				},
				slug: "",
				title: {
					en: "Introduction",
				},
			},
			{
				path: {
					en: "https://raw.githubusercontent.com/floriandwt/inlang-marketplace-test/main/cli/first-page.md",
				},
				slug: "page-1",
				title: {
					en: "Page 1",
				},
			},
			{
				path: {
					en: "https://raw.githubusercontent.com/floriandwt/inlang-marketplace-test/main/cli/second-page.md",
				},
				slug: "page-2",
				title: {
					en: "Page 2",
				},
			},
		],
		keywords: ["cli", "commands"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
	},
]
