const Strings = {
	de: {
		translation: {
			Discovery_Website_subtitle:
				'A&amp;R <ph type="undefined" >asdsad</ph>, Tutorial usw. \nasdasdasd\n\nasd',
			design__empty_list_detail_msg:
				"Etiketten für die Lokalisierung\nwerden hier angezeigt, wenn sie ausgewählt sind...",
			design__empty_list_msg: "Keine Frames ausgewählt",
			file_onboarding__back_button: "Zurück",
			file_onboarding__baselang_cta:
				"Bitte wählen Sie die Sprache aus, in der die Designdatei derzeit geschrieben ist?",
			file_onboarding__baselang_cta_detail: "Bitte wählen Sie die Ausgangssprache.",
			file_onboarding__baselang_detail: "Bitte wählen Sie die Ausgangssprache.",
			file_onboarding__finish_setup_button: "Schließen Sie die Installation ab",
			file_onboarding__languages_cta: "Please select langueages to translate the designfile for.",
			file_onboarding__next_button: "Weiter",
			greeting: "Hallo",
			keys__search_placeholder: "Suche",
			keys__search_result_hint: "{{count}} Übereinstimmungen",
			keys__version__reuse_button: "Wiederverwenden",
			keys__version__title: "Versions Historie",
			l_bg: "bulgarisch",
			l_cs: "Tschechisch",
			l_de: "German",
			l_en: "Englisch",
			l_fr: "Französisch",
			l_it: "Italienisch",
			l_nl: "Niederländisch",
			l_sv: "Schwedisch",
			product_name: "Parrot",
			product_tag_line: "Let Your Designs Speak All Languages\n",
			setup__title: "Cancel",
			tab_Keys: "Schlüssel",
			tab_design: "Design",
			tab_export: "Export",
			tab_import: "Import",
			tab_keys: "Schlüssel",
			tab_setup: "Einstellungen",
		},
	},
	en: {
		translation: {
			Discovery_Website_subtitle: "A&R Intro, Tutorial etc.",
			consumption_paywall_collaboration_explanation:
				"Your plan allows you to use Parrot in this file only––upgrade to levelup others",
			consumption_paywall_collaboration_question: "Up for some teamwork?",
			consumption_paywall_current_plan: "Current plan",
			consumption_paywall_export_explanation:
				"Your plan comes with export for base language––upgrade to export unlimited target languages",
			consumption_paywall_export_question: "Do you want to export the target languages?",
			consumption_paywall_first_plan_export_feature1: "3 Figma design &amp; 3 FigJam files",
			consumption_paywall_first_plan_export_feature2: "1 mode for variables",
			consumption_paywall_first_plan_export_feature3: "Shared team libraries",
			consumption_paywall_first_plan_name: "Starter",
			consumption_paywall_first_plan_price_addition: "for unlimited editors",
			consumption_paywall_first_plan_price_title: "Free",
			consumption_paywall_first_plan_tagline: "For trying things out",
			consumption_paywall_first_plan_upgrade: "Upgrade to Professional",
			consumption_paywall_free_plan_export_feature1: "3 Figma design &amp; 3 FigJam files",
			consumption_paywall_free_plan_export_feature2: "1 mode for variables",
			consumption_paywall_free_plan_name: "Curious designer",
			consumption_paywall_free_plan_price: "Free",
			consumption_paywall_free_plan_price_addition: "for unlimited editors",
			consumption_paywall_free_plan_price_price: "12 €",
			consumption_paywall_free_plan_price_title: "Free",
			consumption_paywall_free_plan_tagline: "For trying things out",
			consumption_paywall_plan_name_start: "Starter",
			consumption_paywall_plan_name_starter: "Starter",
			consumption_paywall_second_plan_upgrade: "Upgrade to Organization",
			consumption_paywall_see_all_features: "See all features",
			design__empty_list_detail_msg: "",
			design__empty_list_msg: "No frames selected",
			design__tooltip__link: "Untranslated Label (click to link)",
			design__tooltip__revert_design: "Revert changes in Design",
			design__tooltip__show_sample_values: "Update Sample Values",
			design__tooltip__unlink: "Linked Label (click to remove link)",
			design__tooltip__update_to_latest: "Update Label with lates version",
			feature_list_current_plan: "Current plan",
			file_onboarding__back_button: "Back",
			file_onboarding__baselang_cta:
				"Please select the language in which the theme file is currently written?",
			file_onboarding__baselang_cta_detail: "Please select the source language.",
			file_onboarding__finish_setup_button: "Complete the installation",
			file_onboarding__languages_cta: "Please select languages ​​to translate the design file for.",
			file_onboarding__next_button: "Next",
			first_plan_name: "Startup",
			first_plan_tagline: "For  you and your team. with unlimited files and all the pro features.",
			free_plan_name: "Free",
			free_plan_tagline: "See your Desings in different Languages and prepare to Localize",
			greeting: "Hello",
			key_choice__title: "Select Key",
			key_title_name: "welcome_title",
			key_view__search_hint: "Search",
			keys__empty_list_detail_msg: "Localized Keys\nwill show up here.",
			keys__empty_list_msg: "No messages yet",
			keys__search_placeholder: "Search",
			keys__search_result_hint: "{{count}} results",
			keys__version__reuse_button: "Reuse",
			keys__version__title: "Version history",
			l_bg: "Bulgarian",
			l_cs: "Czech",
			l_de: "German",
			l_en: "English",
			l_fr: "French",
			l_it: "Italian2",
			l_nl: "Dutch",
			l_sv: "Swedish",
			plugin_store_description:
				'Parrot a powerful plugin that simplifies the translation management process right within Figma. If you deal with multilingual design projects and want to streamline your translation workflow, this plugin is for you!&nbsp;\n\n<strong>Key Features:</strong>\n\n<strong>Design in Different Languages:</strong>&nbsp;Create and manage multiple language versions of your designs within the same Figma file. Say goodbye to swiching interfaces for text and translation managment - all right within figma.\n\n<strong>Translation Keys Made Easy:</strong>&nbsp;With Parrot, managing translation keys has never been more convenient. Assign unique keys to design elements and update them directly within Figma.\n\n<strong>Import from i18Next, Android and iOS:</strong>&nbsp;Seamlessly import existing translation keys from Android and iOS projects or i18Next JSON format to jumpstart your localization efforts.\n\n<strong>Export with Ease:</strong>&nbsp;Effortlessly export your translated content to Android and iOS projects for a smooth handoff to developers. i18Next and CLI support is also coming soon!\n\n<strong>How It Works:</strong>\n\nInstall&nbsp;<a href="https://www.figma.com/community/plugin/1205803482754362456/Parrot-Beta">Parrot from the Figma plugin library</a>.\nSelect any design element you wish to translate and assign a translation key.\nUse Parrot’s intuitive interface to manage translations and update content directly within Figma.\n\n<strong>Why Parrot?</strong>\n\nSave time and effort with in-app translation management.\nCollaborate seamlessly with your team on multilingual projects.\nEmpower developers with translation-ready designs without the need for manual translation key handling.\n\nI’d love to get your feedback on this plugin and how it can be further improved to meet your needs. Feel free to try it out and let me know your thoughts!\n',
			plugin_store_product_name: "Parrot Beta",
			plugin_store_tagline: "Let Your Designs Speak All Languages",
			plugin_store_tags_tag_1: "localisation",
			plugin_store_tags_tag_2: "internationalisation",
			plugin_store_tags_tag_3: "translation",
			plugin_store_tags_tag_4: "translator",
			plugin_store_tags_tag_5: "translate",
			plugin_store_tags_tag_6: "xml",
			plugin_store_tags_tag_7: "deepL",
			product_name: "Parrot",
			product_tag_line: "Let Your Designs Speak <strong>All Languages</strong>",
			second_plan_name: "Professional",
			second_plan_tagline: "For  you and your team. with unlimited files and all the pro features.",
			tab_Keys: "<strong>Keys</strong>",
			tab_design: "Design",
			tab_export: "Export",
			tab_import: "Import",
			tab_keys: "Keys",
			tab_setup: "Setup",
			test: "Design",
		},
	},
};

export default Strings;
