<script>
    import {Tab, TabContent, Tabs} from "carbon-components-svelte";
</script>

<h1>Machine Translations</h1>
<p>Translations can be autogenerated through <a href="https://www.deepl.com/">Deepl</a> for increased productivity of translations.</p>

<p><a href="https://support.deepl.com/hc/en-us/articles/360019925219-Languages-included-in-DeepL-Pro">Deepl supported languages can be seen here.</a></p>

<Tabs>
    <Tab label="Usage"/>
    <Tab label="Settings"/>
    <div slot="content">
        <TabContent>Usage stats</TabContent>
        <TabContent>Settings</TabContent>
    </div>
</Tabs>