/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CPluginsRouteImport } from './routes/c/plugins'
import { Route as CAppsRouteImport } from './routes/c/apps'
import { Route as MUidIndexRouteImport } from './routes/m/$uid/index'
import { Route as MUidSlugIndexRouteImport } from './routes/m/$uid/$slug/index'
import { Route as MUidSlugSplatRouteImport } from './routes/m/$uid/$slug/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CPluginsRoute = CPluginsRouteImport.update({
  id: '/c/plugins',
  path: '/c/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const CAppsRoute = CAppsRouteImport.update({
  id: '/c/apps',
  path: '/c/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const MUidIndexRoute = MUidIndexRouteImport.update({
  id: '/m/$uid/',
  path: '/m/$uid/',
  getParentRoute: () => rootRouteImport,
} as any)
const MUidSlugIndexRoute = MUidSlugIndexRouteImport.update({
  id: '/m/$uid/$slug/',
  path: '/m/$uid/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const MUidSlugSplatRoute = MUidSlugSplatRouteImport.update({
  id: '/m/$uid/$slug/$',
  path: '/m/$uid/$slug/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c/apps': typeof CAppsRoute
  '/c/plugins': typeof CPluginsRoute
  '/m/$uid': typeof MUidIndexRoute
  '/m/$uid/$slug/$': typeof MUidSlugSplatRoute
  '/m/$uid/$slug': typeof MUidSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c/apps': typeof CAppsRoute
  '/c/plugins': typeof CPluginsRoute
  '/m/$uid': typeof MUidIndexRoute
  '/m/$uid/$slug/$': typeof MUidSlugSplatRoute
  '/m/$uid/$slug': typeof MUidSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/c/apps': typeof CAppsRoute
  '/c/plugins': typeof CPluginsRoute
  '/m/$uid/': typeof MUidIndexRoute
  '/m/$uid/$slug/$': typeof MUidSlugSplatRoute
  '/m/$uid/$slug/': typeof MUidSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/c/apps'
    | '/c/plugins'
    | '/m/$uid'
    | '/m/$uid/$slug/$'
    | '/m/$uid/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/c/apps'
    | '/c/plugins'
    | '/m/$uid'
    | '/m/$uid/$slug/$'
    | '/m/$uid/$slug'
  id:
    | '__root__'
    | '/'
    | '/c/apps'
    | '/c/plugins'
    | '/m/$uid/'
    | '/m/$uid/$slug/$'
    | '/m/$uid/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CAppsRoute: typeof CAppsRoute
  CPluginsRoute: typeof CPluginsRoute
  MUidIndexRoute: typeof MUidIndexRoute
  MUidSlugSplatRoute: typeof MUidSlugSplatRoute
  MUidSlugIndexRoute: typeof MUidSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/plugins': {
      id: '/c/plugins'
      path: '/c/plugins'
      fullPath: '/c/plugins'
      preLoaderRoute: typeof CPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/apps': {
      id: '/c/apps'
      path: '/c/apps'
      fullPath: '/c/apps'
      preLoaderRoute: typeof CAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$uid/': {
      id: '/m/$uid/'
      path: '/m/$uid'
      fullPath: '/m/$uid'
      preLoaderRoute: typeof MUidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$uid/$slug/': {
      id: '/m/$uid/$slug/'
      path: '/m/$uid/$slug'
      fullPath: '/m/$uid/$slug'
      preLoaderRoute: typeof MUidSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$uid/$slug/$': {
      id: '/m/$uid/$slug/$'
      path: '/m/$uid/$slug/$'
      fullPath: '/m/$uid/$slug/$'
      preLoaderRoute: typeof MUidSlugSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CAppsRoute: CAppsRoute,
  CPluginsRoute: CPluginsRoute,
  MUidIndexRoute: MUidIndexRoute,
  MUidSlugSplatRoute: MUidSlugSplatRoute,
  MUidSlugIndexRoute: MUidSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
