import type { Metadata } from "next"
import { languageTag } from "@inlang/paraglide-js"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang={languageTag}>
			<body>{children}</body>
		</html>
	)
}
