//! Do not edit this file manually. It is automatically generated based on the contents of the registry.json file.

import type { MarketplaceManifest } from "@inlang/marketplace-manifest"
export const registry: MarketplaceManifest[] = [
	{
		id: "app.inlang.cli",
		icon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		displayName: {
			en: "inlang CLI",
		},
		description: {
			en: "Official inlang CLI",
		},
		readme: {
			en: "https://raw.githubusercontent.com/inlang/inlang/main/source-code/cli/README.md",
		},
		keywords: ["cli", "commands"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
	},
	{
		id: "lintRule.inlang.emptyPattern",
		icon: "https://raw.githubusercontent.com/inlang/inlang/main/source-code/plugins/standard-lint-rules/assets/icon.png",
		displayName: {
			en: "Empty Pattern",
		},
		description: {
			en: "Checks for empty pattern in a language tag. If a message exists in the reference resource but the pattern in a target resource is empty, it is likely that the message has not been translated yet.",
		},
		readme: {
			en: "https://github.com/inlang/inlang/blob/main/source-code/lint-rules/emptyPattern/README.md",
		},
		keywords: ["lint rule", "empty pattern"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
		module: "../../plugins/emptyPattern/emptyPattern.js",
	},
	{
		id: "lintRule.inlang.identicalPattern",
		icon: "https://raw.githubusercontent.com/inlang/inlang/main/source-code/plugins/standard-lint-rules/assets/icon.png",
		displayName: {
			en: "Identical Pattern",
		},
		description: {
			en: "Checks for identical patterns in different languages.  A message with identical wording in multiple languages can indicate that the translations are redundant or can be combined into a single message to reduce translation effort.",
		},
		readme: {
			en: "https://raw.githubusercontent.com/inlang/inlang/armageddon/source-code/lint-rules/identicalPattern/README.md",
		},
		keywords: ["lint rule", "itentical pattern"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
		module: "../../plugins/identicalPattern/identicalPattern.js",
	},
	{
		id: "lintRule.inlang.messageWithoutSource",
		icon: "https://raw.githubusercontent.com/inlang/inlang/main/source-code/plugins/standard-lint-rules/assets/icon.png",
		displayName: {
			en: "Message without source",
		},
		description: {
			en: "Checks for likely outdated messages.  A message with a missing source is usually an indication that the message (id) is no longer used in source code, but messages have not been updated accordingly.",
		},
		readme: {
			en: "https://raw.githubusercontent.com/inlang/inlang/armageddon/source-code/lint-rules/messageWithoutSource/README.md",
		},
		keywords: ["lint rule", "source"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
		module: "../../plugins/messageWithoutSource/messageWithoutSource.js",
	},
	{
		id: "plugin.inlang.i18next",
		icon: "https://github.com/inlang/inlang/blob/main/source-code/plugins/i18next/assets/icon.png?raw=true",
		displayName: {
			en: "i18next",
		},
		description: {
			en: "i18next plugin for inlang",
		},
		readme: {
			en: "https://raw.githubusercontent.com/inlang/inlang/main/source-code/plugins/json/README.md",
		},
		keywords: ["i18next", "react", "nextjs"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
		module: "./i18next/dist/index.js",
	},
	{
		id: "plugin.inlang.json",
		icon: "https://github.com/inlang/inlang/blob/main/source-code/plugins/json/assets/icon.png?raw=true",
		displayName: {
			en: "JSON translation files",
		},
		description: {
			en: "JSON plugin for inlang",
		},
		readme: {
			en: "https://raw.githubusercontent.com/inlang/inlang/main/source-code/plugins/json/README.md",
		},
		keywords: ["json", "generic"],
		publisherName: "inlang",
		publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		license: "Apache-2.0",
		module: "../../plugins/json/dist/index.js",
	},
]
