// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType } from 'typesafe-i18n'
import type { LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'da'
	| 'de'
	| 'en'
	| 'fr'
	| 'nl'

export type Translation = {
	/**
	 * Select a language
	 */
	'selectLanguage': string
	/**
	 * ⭐ Star inlang on GitHub
	 */
	'starOnGithub': string
	/**
	 * Welcome to the inlang example
	 */
	'welcome': string
	'index': {	
		/**
		 * 1. This card is already localized by us
		 */
		'firstCard': string
	}
	/**
	 * What is your name?
	 */
	'askName': string
	/**
	 * What is your favorite color?
	 */
	'askFavoriteColor': string
	/**
	 * enter your name
	 */
	'enterName': string
	/**
	 * My name is {name} and my favorite color is {color}.
	 * @param {unknown} color
	 * @param {unknown} name
	 */
	'nameAndFavoriteColor': RequiredParams2<'color', 'name'>
	'footer': {	
		/**
		 * Inlang is in early alpha
		 */
		'inlangAlpha': string
		/**
		 * Every feedback we get helps us tremendously.
		 */
		'feedback': string
		/**
		 * Do you have feedback on this example?
		 */
		'bromb': string
	}
}

export type TranslationFunctions = {
	/**
	 * Select a language
	 */
	'selectLanguage': () => LocalizedString
	/**
	 * ⭐ Star inlang on GitHub
	 */
	'starOnGithub': () => LocalizedString
	/**
	 * Welcome to the inlang example
	 */
	'welcome': () => LocalizedString
	'index': {	
		/**
		 * 1. This card is already localized by us
		 */
		'firstCard': () => LocalizedString
	}
	/**
	 * What is your name?
	 */
	'askName': () => LocalizedString
	/**
	 * What is your favorite color?
	 */
	'askFavoriteColor': () => LocalizedString
	/**
	 * enter your name
	 */
	'enterName': () => LocalizedString
	/**
	 * My name is {name} and my favorite color is {color}.
	 */
	'nameAndFavoriteColor': (arg: { color: unknown, name: unknown }) => LocalizedString
	'footer': {	
		/**
		 * Inlang is in early alpha
		 */
		'inlangAlpha': () => LocalizedString
		/**
		 * Every feedback we get helps us tremendously.
		 */
		'feedback': () => LocalizedString
		/**
		 * Do you have feedback on this example?
		 */
		'bromb': () => LocalizedString
	}
}

export type Formatters = {}

type Param<P extends string> = `{${P}}`

type Params2<P1 extends string, P2 extends string> =
	`${string}${Param<P1>}${string}${Param<P2>}${string}`

type RequiredParams2<P1 extends string, P2 extends string> =
	| Params2<P1, P2>
	| Params2<P2, P1>
